# Generated by Django 4.1.7 on 2023-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selleremail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
