# Generated by Django 4.1.7 on 2023-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_orderitem_selleremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selleremail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
